services:
    postgres:
        image: "postgres:13-alpine"
        hostname: postgres
        environment:
            POSTGRES_PASSWORD: demo
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro